algoritmo "EX11"
// Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
//segundo grau e mostre o valor de Delta.
var
   A, B, C: inteiro
   delta: real
inicio
      escreva("Digite um valor para A:")
      leia(a)
      escreva("Digite um valor para B:")
      leia(b)
      escreva("Digite um valor para C:")
      leia(c)
      
      delta <- b^2(-4)*A*C
      
      escreval("O valor de delta é igual a == ",delta)

fimalgoritmo